import { action, internalAction, internalMutation } from "./_generated/server";
import { v } from "convex/values";
import { api, internal } from "./_generated/api";

// ─── Internal mutations ───────────────────────────────────────────────────────

export const updateResearchStatus = internalMutation({
  args: {
    companyId: v.id("outreachCompanies"),
    status: v.union(
      v.literal("pending"),
      v.literal("researching"),
      v.literal("done"),
      v.literal("failed")
    ),
    summary: v.optional(v.string()),
  },
  handler: async (ctx, { companyId, status, summary }) => {
    const patch: Record<string, unknown> = { researchStatus: status, updatedAt: Date.now() };
    if (summary !== undefined) patch.researchSummary = summary;
    await ctx.db.patch(companyId, patch);
  },
});

export const enrichCompany = internalMutation({
  args: {
    companyId: v.id("outreachCompanies"),
    domain: v.optional(v.string()),
    logoUrl: v.optional(v.string()),
    linkedinUrl: v.optional(v.string()),
    websiteUrl: v.optional(v.string()),
    isYcBacked: v.optional(v.boolean()),
    careersUrl: v.optional(v.string()),
    description: v.optional(v.string()),
    employeeCount: v.optional(v.number()),
    industry: v.optional(v.string()),
    fundingStage: v.optional(v.string()),
  },
  handler: async (ctx, { companyId, ...fields }) => {
    const patch: Record<string, unknown> = { updatedAt: Date.now() };
    for (const [k, val] of Object.entries(fields)) {
      if (val !== undefined && val !== null) patch[k] = val;
    }
    await ctx.db.patch(companyId, patch);
  },
});

export const finalizeResearch = internalMutation({
  args: { companyId: v.id("outreachCompanies") },
  handler: async (ctx, { companyId }) => {
    const company = await ctx.db.get(companyId);
    if (!company) return;

    const jobs = await ctx.db
      .query("outreachJobs")
      .withIndex("by_company", (q) => q.eq("companyId", companyId))
      .collect();

    const contacts = await ctx.db
      .query("outreachContacts")
      .withIndex("by_company", (q) => q.eq("companyId", companyId))
      .collect();

    const existingSteps = await ctx.db
      .query("outreachSteps")
      .withIndex("by_company", (q) => q.eq("companyId", companyId))
      .collect();

    const existingLabels = existingSteps.map((s) => s.label.toLowerCase());
    const hasLabel = (keyword: string) =>
      existingLabels.some((l) => l.includes(keyword.toLowerCase()));

    const now = Date.now();
    let order = existingSteps.length;

    const stepsToAdd: string[] = [];

    if (jobs.some((j) => j.source === "linkedin") && !hasLabel("linkedin")) {
      stepsToAdd.push("Apply on LinkedIn");
    }
    if (company.careersUrl && !hasLabel("company portal") && !hasLabel("careers")) {
      stepsToAdd.push("Apply on company portal");
    }
    if (company.isYcBacked && !hasLabel("yc")) {
      stepsToAdd.push("Apply via YC portal");
    }
    if (contacts.some((c) => c.email) && !hasLabel("cold email")) {
      stepsToAdd.push("Send cold emails");
    }
    if (contacts.some((c) => c.linkedinUrl) && !hasLabel("linkedin dm")) {
      stepsToAdd.push("Send LinkedIn DMs");
    }

    for (const label of stepsToAdd) {
      await ctx.db.insert("outreachSteps", {
        companyId,
        label,
        status: "pending",
        order: order++,
        isAutoGenerated: true,
        updatedAt: now,
      });
    }

    const summary = `Research complete: ${jobs.length} job${jobs.length !== 1 ? "s" : ""} found, ${contacts.length} contact${contacts.length !== 1 ? "s" : ""} found.`;
    await ctx.db.patch(companyId, {
      researchStatus: "done",
      researchSummary: summary,
      updatedAt: now,
    });
    console.log(`[FINALIZE] ${summary}`);
  },
});

// ─── Job Discovery (internal action) ─────────────────────────────────────────

export const discoverJobs = internalAction({
  args: {
    companyId: v.id("outreachCompanies"),
    companyName: v.string(),
    domain: v.optional(v.string()),
    isYcBacked: v.boolean(),
  },
  handler: async (ctx, { companyId, companyName, domain, isYcBacked }) => {
    type JobPayload = {
      companyId: typeof companyId;
      title: string;
      url: string;
      source: "linkedin" | "careers_page" | "greenhouse" | "lever" | "ashby" | "workable" | "yc" | "wellfound" | "instahyre" | "naukri";
      location?: string;
      description?: string;
    };

    const discovered: JobPayload[] = [];
    console.log(`\n[JOBS] ========== Starting job discovery for "${companyName}" ==========`);
    console.log(`[JOBS] Domain: ${domain || "unknown"}`);

    if (!domain) {
      console.log(`[JOBS] No domain — skipping ATS and careers scraping`);
      await ctx.runMutation(internal.companyResearch.finalizeResearch, { companyId });
      return;
    }

    const companySlug = domain.split(".")[0];
    const companySlugClean = companyName.toLowerCase().replace(/[^a-z0-9]/g, "");
    const slugsToTry = [...new Set([companySlug, companySlugClean])];

    // ── Source 1: Greenhouse API (free, unlimited, no auth) ──
    for (const slug of slugsToTry) {
      try {
        console.log(`[JOBS] Trying Greenhouse: boards-api.greenhouse.io/v1/boards/${slug}/jobs`);
        const res = await fetch(`https://boards-api.greenhouse.io/v1/boards/${slug}/jobs?content=true`, {
          headers: { "User-Agent": "Mozilla/5.0" },
        });
        if (res.ok) {
          const data = await res.json();
          const realJobs = (data.jobs || []).filter((j: any) =>
            !/\btest\b/i.test(j.title) && !/^EA\b/.test(j.title) && j.title.length > 5
          );
          for (const job of realJobs.slice(0, 20)) {
            discovered.push({
              companyId,
              title: job.title,
              url: job.absolute_url || `https://boards.greenhouse.io/${slug}/jobs/${job.id}`,
              source: "greenhouse",
              location: job.location?.name,
              description: (job.content || "").replace(/<[^>]*>/g, "").slice(0, 2000),
            });
          }
          if (realJobs.length > 0) {
            console.log(`[JOBS] ✅ Greenhouse (${slug}): ${realJobs.length} jobs found`);
            break;
          }
          console.log(`[JOBS] ⚠️ Greenhouse (${slug}): ${data.jobs?.length || 0} total, ${realJobs.length} after filtering test jobs`);
        } else {
          console.log(`[JOBS] ❌ Greenhouse (${slug}): ${res.status}`);
        }
      } catch (e: any) {
        console.log(`[JOBS] ❌ Greenhouse (${slug}): ${e.message}`);
      }
    }

    // ── Source 2: Lever API (free, unlimited, no auth) ──
    if (discovered.length === 0) {
      for (const slug of slugsToTry) {
        try {
          console.log(`[JOBS] Trying Lever: api.lever.co/v0/postings/${slug}`);
          const res = await fetch(`https://api.lever.co/v0/postings/${slug}?mode=json`, {
            headers: { "User-Agent": "Mozilla/5.0" },
          });
          if (res.ok) {
            const jobs = await res.json();
            if (Array.isArray(jobs) && jobs.length > 0) {
              for (const job of jobs.slice(0, 20)) {
                discovered.push({
                  companyId,
                  title: job.text,
                  url: job.hostedUrl || job.applyUrl,
                  source: "lever",
                  location: job.categories?.location,
                  description: job.descriptionPlain?.slice(0, 2000),
                });
              }
              console.log(`[JOBS] ✅ Lever (${slug}): ${jobs.length} jobs found`);
              break;
            }
          } else {
            console.log(`[JOBS] ❌ Lever (${slug}): ${res.status}`);
          }
        } catch (e: any) {
          console.log(`[JOBS] ❌ Lever (${slug}): ${e.message}`);
        }
      }
    }

    // ── Source 3: Workable API (free, unlimited, no auth) ──
    if (discovered.length === 0) {
      for (const slug of slugsToTry) {
        try {
          console.log(`[JOBS] Trying Workable: apply.workable.com/api/v1/widget/accounts/${slug}`);
          const res = await fetch(`https://apply.workable.com/api/v1/widget/accounts/${slug}`, {
            headers: { "User-Agent": "Mozilla/5.0" },
          });
          if (res.ok) {
            const data = await res.json();
            const jobs = data.jobs || [];
            for (const job of jobs.slice(0, 20)) {
              discovered.push({
                companyId,
                title: job.title,
                url: `https://apply.workable.com/${slug}/j/${job.shortcode}/`,
                source: "workable",
                location: [job.city, job.state, job.country].filter(Boolean).join(", "),
              });
            }
            if (jobs.length > 0) {
              console.log(`[JOBS] ✅ Workable (${slug}): ${jobs.length} jobs found`);
              break;
            }
          } else {
            console.log(`[JOBS] ❌ Workable (${slug}): ${res.status}`);
          }
        } catch (e: any) {
          console.log(`[JOBS] ❌ Workable (${slug}): ${e.message}`);
        }
      }
    }

    // ── Source 4: Careers page scraping (fallback) ──
    if (discovered.length === 0) {
      const urlsToTry = [
        `https://${domain}/careers`,
        `https://${domain}/jobs`,
        `https://www.${domain}/careers`,
        `https://www.${domain}/jobs`,
        `https://${domain}/careers/openings`,
      ];
      for (const url of urlsToTry) {
        try {
          console.log(`[JOBS] Trying careers page: ${url}`);
          const res = await fetch(url, {
            headers: { "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36" },
            redirect: "follow",
          });
          if (!res.ok) {
            console.log(`[JOBS] ❌ ${url}: ${res.status}`);
            continue;
          }
          const html = await res.text();
          const finalUrl = res.url;
          console.log(`[JOBS] 📄 Scraped ${finalUrl} (${html.length} bytes)`);

          // Check if it redirected to a known ATS
          const ghMatch = finalUrl.match(/boards\.greenhouse\.io\/(\w+)/) || html.match(/boards\.greenhouse\.io\/(\w+)/);
          const leverMatch = finalUrl.match(/jobs\.lever\.co\/([^/"'\s]+)/) || html.match(/jobs\.lever\.co\/([^/"'\s]+)/);

          if (ghMatch) {
            console.log(`[JOBS] 🔀 Redirected to Greenhouse: ${ghMatch[1]}`);
            const ghRes = await fetch(`https://boards-api.greenhouse.io/v1/boards/${ghMatch[1]}/jobs?content=true`);
            if (ghRes.ok) {
              const data = await ghRes.json();
              const realJobs = (data.jobs || []).filter((j: any) => !/\btest\b/i.test(j.title) && j.title.length > 5);
              for (const job of realJobs.slice(0, 20)) {
                discovered.push({ companyId, title: job.title, url: job.absolute_url, source: "greenhouse", location: job.location?.name });
              }
              console.log(`[JOBS] ✅ Greenhouse via redirect: ${realJobs.length} jobs`);
            }
          } else if (leverMatch) {
            console.log(`[JOBS] 🔀 Redirected to Lever: ${leverMatch[1]}`);
            const levRes = await fetch(`https://api.lever.co/v0/postings/${leverMatch[1]}?mode=json`);
            if (levRes.ok) {
              const jobs = await levRes.json();
              if (Array.isArray(jobs)) {
                for (const job of jobs.slice(0, 20)) {
                  discovered.push({ companyId, title: job.text, url: job.hostedUrl, source: "lever", location: job.categories?.location });
                }
                console.log(`[JOBS] ✅ Lever via redirect: ${jobs.length} jobs`);
              }
            }
          } else {
            // Generic HTML scraping
            const jobPattern = /<a[^>]+href=["']([^"']*(?:\/jobs?\/|\/positions?\/|\/careers?\/|\/openings?\/|\/apply\/)[^"']*)["'][^>]*>([^<]{5,120})<\/a>/gi;
            let match: RegExpExecArray | null;
            const seenTitles = new Set<string>();
            while ((match = jobPattern.exec(html)) !== null) {
              const text = match[2].trim().replace(/\s+/g, " ");
              if (seenTitles.has(text.toLowerCase())) continue;
              if (/^(about|blog|contact|privacy|terms|login|sign|home)/i.test(text)) continue;
              seenTitles.add(text.toLowerCase());
              const href = match[1].startsWith("http") ? match[1] : `https://${new URL(finalUrl).hostname}${match[1]}`;
              discovered.push({ companyId, title: text, url: href, source: "careers_page" });
              if (discovered.length >= 20) break;
            }
            console.log(`[JOBS] 📄 HTML scraping found ${discovered.length} job links`);
          }

          if (discovered.length > 0) {
            await ctx.runMutation(internal.companyResearch.enrichCompany, { companyId, careersUrl: url });
            break;
          }
        } catch (e: any) {
          console.log(`[JOBS] ❌ ${url}: ${e.message}`);
        }
      }
    }

    // ── Source 5: YC Work at a Startup ──
    if (isYcBacked) {
      try {
        console.log(`[JOBS] Trying YC Work at a Startup for "${companyName}"`);
        const ycRes = await fetch(
          `https://www.workatastartup.com/companies?q=${encodeURIComponent(companyName)}`,
          { headers: { "User-Agent": "Mozilla/5.0" } }
        );
        if (ycRes.ok) {
          const html = await ycRes.text();
          const jobPattern = /<a[^>]+href=["'](\/jobs\/\d+)["'][^>]*>([^<]{5,120})<\/a>/gi;
          let match: RegExpExecArray | null;
          while ((match = jobPattern.exec(html)) !== null) {
            discovered.push({ companyId, title: match[2].trim(), url: `https://www.workatastartup.com${match[1]}`, source: "yc" });
          }
          console.log(`[JOBS] YC found ${discovered.filter((j) => j.source === "yc").length} jobs`);
        }
      } catch { /* YC failed */ }
    }

    console.log(`[JOBS] ========== Total: ${discovered.length} jobs discovered ==========\n`);

    if (discovered.length > 0) {
      await ctx.runMutation(internal.outreachJobs.batchCreate, { jobs: discovered });
    }

    await ctx.runMutation(internal.companyResearch.finalizeResearch, { companyId });
  },
});

// ─── Contact Discovery (internal action) ─────────────────────────────────────

export const findContacts = internalAction({
  args: {
    companyId: v.id("outreachCompanies"),
    companyName: v.string(),
    domain: v.optional(v.string()),
    tier: v.optional(v.union(v.literal("tier1"), v.literal("tier2"), v.literal("tier3"))),
  },
  handler: async (ctx, { companyId, companyName, domain, tier }) => {
    const apolloKey = process.env.APOLLO_API_KEY;
    console.log(`\n[CONTACTS] ========== Finding contacts for "${companyName}" ==========`);
    console.log(`[CONTACTS] Domain: ${domain || "unknown"}, Apollo key: ${apolloKey ? "set" : "MISSING"}`);

    if (!apolloKey) {
      console.log(`[CONTACTS] ❌ No Apollo API key — cannot search for contacts`);
      await ctx.runMutation(internal.companyResearch.finalizeResearch, { companyId });
      return;
    }

    const tier1Titles = [
      "CTO", "VP Engineering", "Head of Engineering",
      "Director of Engineering", "Engineering Manager",
      "Senior Engineering Manager", "Founder", "CEO", "Co-founder",
      "Chief Product Officer", "VP Product",
    ];
    const tier2Titles = [
      "Recruiter", "Senior Recruiter", "Lead Recruiter",
      "Talent Acquisition", "Head of Talent",
      "HR Manager", "People Operations", "Technical Recruiter",
    ];
    const tier3Titles = [
      "Senior Engineer", "Staff Engineer", "Team Lead", "Principal Engineer",
    ];

    const targetTitles = tier === "tier2" ? tier2Titles
      : tier === "tier3" ? tier3Titles
      : [...tier1Titles, ...tier2Titles];

    const tierForTitle = (title: string): "tier1" | "tier2" | "tier3" => {
      if (tier === "tier3") return "tier3";
      const t = title.toLowerCase();
      if (tier2Titles.some((tt) => t.includes(tt.toLowerCase()))) return "tier2";
      return "tier1";
    };

    // ── Apollo People Search ──
    // KEY: Use q_organization_name (works WITHOUT domain) instead of q_organization_domains
    try {
      const searchBody: Record<string, unknown> = {
        q_titles: targetTitles,
        per_page: 10,
      };

      // Use organization name as primary search (works even without domain)
      if (domain) {
        searchBody.q_organization_domains = domain;
        console.log(`[CONTACTS] Apollo search: domain="${domain}", titles=${targetTitles.length}`);
      } else {
        searchBody.q_organization_name = companyName;
        console.log(`[CONTACTS] Apollo search: company name="${companyName}" (no domain), titles=${targetTitles.length}`);
      }

      const res = await fetch("https://api.apollo.io/api/v1/mixed_people/search", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Api-Key": apolloKey,
        },
        body: JSON.stringify(searchBody),
      });

      console.log(`[CONTACTS] Apollo response: ${res.status}`);

      if (!res.ok) {
        const errText = await res.text().catch(() => "");
        console.log(`[CONTACTS] ❌ Apollo error: ${res.status} — ${errText.slice(0, 200)}`);

        // Retry with company name if domain search failed
        if (domain) {
          console.log(`[CONTACTS] Retrying with company name instead of domain...`);
          const retryRes = await fetch("https://api.apollo.io/api/v1/mixed_people/search", {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              "X-Api-Key": apolloKey,
            },
            body: JSON.stringify({
              q_organization_name: companyName,
              q_titles: targetTitles,
              per_page: 10,
            }),
          });
          console.log(`[CONTACTS] Apollo retry response: ${retryRes.status}`);

          if (retryRes.ok) {
            const retryData = await retryRes.json();
            await processApolloResults(ctx, companyId, retryData.people || [], tierForTitle);
          }
        }

        await ctx.runMutation(internal.companyResearch.finalizeResearch, { companyId });
        return;
      }

      const data = await res.json();
      const people = data.people || [];
      console.log(`[CONTACTS] Apollo returned ${people.length} people`);

      await processApolloResults(ctx, companyId, people, tierForTitle);
    } catch (e: any) {
      console.error(`[CONTACTS] ❌ Apollo search failed: ${e.message}`);
    }

    // ── Hunter.io fallback for emails (if we have domain) ──
    const hunterKey = process.env.HUNTER_API_KEY;
    if (hunterKey && domain) {
      try {
        console.log(`[CONTACTS] Trying Hunter.io for ${domain}`);
        const res = await fetch(
          `https://api.hunter.io/v2/domain-search?domain=${domain}&api_key=${hunterKey}&limit=5`
        );
        if (res.ok) {
          const data = await res.json();
          const emails = data.data?.emails || [];
          console.log(`[CONTACTS] Hunter.io found ${emails.length} emails`);
          // These are supplementary — we'd need to match them to existing contacts
        }
      } catch {
        console.log(`[CONTACTS] ❌ Hunter.io failed`);
      }
    }

    console.log(`[CONTACTS] ========== Contact discovery complete ==========\n`);
    await ctx.runMutation(internal.companyResearch.finalizeResearch, { companyId });
  },
});

async function processApolloResults(
  ctx: any,
  companyId: any,
  people: any[],
  tierForTitle: (title: string) => "tier1" | "tier2" | "tier3"
) {
  for (const person of people) {
    const name = person.name ?? [person.first_name, person.last_name].filter(Boolean).join(" ");
    if (!name) continue;

    const assignedTier = tierForTitle(person.title || "");
    console.log(
      `[CONTACTS] ✅ ${name} — ${person.title || "no title"} (${assignedTier}) | ` +
      `email=${person.email ? "✓" : "✗"} | phone=${person.phone_numbers?.[0] ? "✓" : "✗"} | ` +
      `linkedin=${person.linkedin_url ? "✓" : "✗"}`
    );

    await ctx.runMutation(internal.outreachContacts.createFromResearch, {
      companyId,
      name,
      title: person.title,
      linkedinUrl: person.linkedin_url,
      email: person.email,
      phone: person.phone_numbers?.[0]?.sanitized_number,
      profilePictureUrl: person.photo_url,
      headline: person.headline,
      source: "apollo" as const,
      tier: assignedTier,
    });
  }
}

// ─── Public action ────────────────────────────────────────────────────────────

export const researchCompany = action({
  args: {
    companyId: v.id("outreachCompanies"),
    input: v.optional(v.string()),
  },
  handler: async (ctx, { companyId, input }) => {
    console.log(`\n╔══════════════════════════════════════════╗`);
    console.log(`║  RESEARCH STARTING                        ║`);
    console.log(`║  Input: ${(input || "none").slice(0, 35).padEnd(35)}║`);
    console.log(`╚══════════════════════════════════════════╝`);

    await ctx.runMutation(internal.companyResearch.updateResearchStatus, {
      companyId,
      status: "researching",
    });

    const company = await ctx.runQuery(api.outreachCompanies.get, { id: companyId });
    if (!company) throw new Error("Company not found");

    let domain = company.domain;
    let linkedinUrl = company.linkedinUrl;
    let websiteUrl = company.websiteUrl;

    console.log(`[RESEARCH] Company: "${company.name}"`);
    console.log(`[RESEARCH] Existing: domain=${domain}, linkedin=${linkedinUrl}, website=${websiteUrl}`);

    // ── Step 1: Resolve company identity ──
    // Use Apollo to enrich from company name or LinkedIn URL
    const apolloKey = process.env.APOLLO_API_KEY;

    if (apolloKey && (!domain || !linkedinUrl)) {
      console.log(`[RESEARCH] Step 1: Apollo Organization Enrich`);

      // Detect input type
      let apolloQuery: Record<string, string> = {};
      if (input?.includes("linkedin.com/company/")) {
        linkedinUrl = input.startsWith("http") ? input : `https://${input}`;
        apolloQuery = { linkedin_url: linkedinUrl };
        console.log(`[RESEARCH] → Using LinkedIn URL for Apollo: ${linkedinUrl}`);
      } else if (input && input.includes(".") && !input.includes(" ")) {
        const url = input.startsWith("http") ? input : `https://${input}`;
        try {
          domain = new URL(url).hostname.replace("www.", "");
          websiteUrl = url;
          apolloQuery = { domain };
          console.log(`[RESEARCH] → Using domain for Apollo: ${domain}`);
        } catch {
          apolloQuery = { name: input };
        }
      } else {
        apolloQuery = { name: input || company.name };
        console.log(`[RESEARCH] → Using company name for Apollo: ${apolloQuery.name}`);
      }

      try {
        const orgRes = await fetch("https://api.apollo.io/api/v1/organizations/enrich", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-Api-Key": apolloKey,
          },
          body: JSON.stringify(apolloQuery),
        });

        console.log(`[RESEARCH] Apollo org enrich response: ${orgRes.status}`);

        if (orgRes.ok) {
          const orgData = await orgRes.json();
          const org = orgData.organization;
          if (org) {
            domain = domain || org.primary_domain || org.website_url?.replace(/^https?:\/\//, "").replace(/\/.*/, "").replace("www.", "");
            linkedinUrl = linkedinUrl || org.linkedin_url;
            websiteUrl = websiteUrl || (org.website_url ? org.website_url : domain ? `https://${domain}` : undefined);

            console.log(`[RESEARCH] ✅ Apollo org enriched:`);
            console.log(`[RESEARCH]   Domain: ${domain}`);
            console.log(`[RESEARCH]   LinkedIn: ${linkedinUrl}`);
            console.log(`[RESEARCH]   Website: ${websiteUrl}`);
            console.log(`[RESEARCH]   Employees: ${org.estimated_num_employees || "unknown"}`);
            console.log(`[RESEARCH]   Industry: ${org.industry || "unknown"}`);

            await ctx.runMutation(internal.companyResearch.enrichCompany, {
              companyId,
              domain,
              logoUrl: org.logo_url || (domain ? `https://logo.clearbit.com/${domain}` : undefined),
              linkedinUrl,
              websiteUrl,
              description: org.short_description || org.seo_description,
              employeeCount: org.estimated_num_employees,
              industry: org.industry,
              fundingStage: org.latest_funding_stage,
            });
          } else {
            console.log(`[RESEARCH] ⚠️ Apollo returned no organization data`);
          }
        } else {
          const errText = await orgRes.text().catch(() => "");
          console.log(`[RESEARCH] ❌ Apollo org enrich failed: ${orgRes.status} — ${errText.slice(0, 200)}`);
        }
      } catch (e: any) {
        console.log(`[RESEARCH] ❌ Apollo org enrich error: ${e.message}`);
      }
    }

    // Fallback: guess domain from company name
    if (!domain) {
      const guesses = [
        company.name.toLowerCase().replace(/[^a-z0-9]/g, "") + ".com",
        company.name.toLowerCase().replace(/[^a-z0-9]/g, "") + ".io",
      ];
      for (const guess of guesses) {
        try {
          console.log(`[RESEARCH] Trying domain guess: ${guess}`);
          const testRes = await fetch(`https://${guess}`, {
            method: "HEAD",
            headers: { "User-Agent": "Mozilla/5.0" },
            redirect: "follow",
          });
          if (testRes.ok || testRes.status === 301 || testRes.status === 302) {
            domain = guess;
            websiteUrl = `https://${guess}`;
            console.log(`[RESEARCH] ✅ Domain confirmed: ${domain}`);
            await ctx.runMutation(internal.companyResearch.enrichCompany, {
              companyId,
              domain,
              websiteUrl,
              logoUrl: `https://logo.clearbit.com/${domain}`,
            });
            break;
          }
        } catch { /* try next */ }
      }
    }

    // ── Step 2: Check YC ──
    let isYcBacked = company.isYcBacked;
    if (!isYcBacked) {
      try {
        console.log(`[RESEARCH] Checking YC for "${company.name}"...`);
        const ycRes = await fetch(
          `https://www.ycombinator.com/companies?q=${encodeURIComponent(company.name)}`,
          { headers: { "User-Agent": "Mozilla/5.0" } }
        );
        if (ycRes.ok) {
          const html = await ycRes.text();
          isYcBacked = html.toLowerCase().includes(company.name.toLowerCase());
          console.log(`[RESEARCH] YC backed: ${isYcBacked}`);
          if (isYcBacked) {
            await ctx.runMutation(internal.companyResearch.enrichCompany, { companyId, isYcBacked: true });
          }
        }
      } catch {
        console.log(`[RESEARCH] YC check failed`);
      }
    }

    // ── Step 3: Schedule parallel discovery ──
    console.log(`[RESEARCH] Scheduling parallel: discoverJobs + findContacts`);
    console.log(`[RESEARCH] → Jobs: domain=${domain}, isYcBacked=${isYcBacked}`);
    console.log(`[RESEARCH] → Contacts: companyName="${company.name}", domain=${domain}`);

    await ctx.scheduler.runAfter(0, internal.companyResearch.discoverJobs, {
      companyId,
      companyName: company.name,
      domain,
      isYcBacked,
    });

    await ctx.scheduler.runAfter(0, internal.companyResearch.findContacts, {
      companyId,
      companyName: company.name,
      domain,
      tier: "tier1",
    });

    console.log(`[RESEARCH] ✅ Research orchestration complete — parallel tasks scheduled`);
  },
});
