import { action, internalAction, internalMutation } from "./_generated/server";
import { v } from "convex/values";
import { api, internal } from "./_generated/api";

// ─── Internal mutations ───────────────────────────────────────────────────────

export const updateResearchStatus = internalMutation({
  args: {
    companyId: v.id("outreachCompanies"),
    status: v.union(
      v.literal("pending"),
      v.literal("researching"),
      v.literal("done"),
      v.literal("failed")
    ),
    summary: v.optional(v.string()),
  },
  handler: async (ctx, { companyId, status, summary }) => {
    const patch: Record<string, unknown> = { researchStatus: status, updatedAt: Date.now() };
    if (summary !== undefined) patch.researchSummary = summary;
    await ctx.db.patch(companyId, patch);
  },
});

export const enrichCompany = internalMutation({
  args: {
    companyId: v.id("outreachCompanies"),
    domain: v.optional(v.string()),
    logoUrl: v.optional(v.string()),
    linkedinUrl: v.optional(v.string()),
    websiteUrl: v.optional(v.string()),
    isYcBacked: v.optional(v.boolean()),
    careersUrl: v.optional(v.string()),
    description: v.optional(v.string()),
    employeeCount: v.optional(v.number()),
    industry: v.optional(v.string()),
    fundingStage: v.optional(v.string()),
  },
  handler: async (ctx, { companyId, ...fields }) => {
    const patch: Record<string, unknown> = { updatedAt: Date.now() };
    for (const [k, val] of Object.entries(fields)) {
      if (val !== undefined) patch[k] = val;
    }
    await ctx.db.patch(companyId, patch);
  },
});

export const finalizeResearch = internalMutation({
  args: { companyId: v.id("outreachCompanies") },
  handler: async (ctx, { companyId }) => {
    const company = await ctx.db.get(companyId);
    if (!company) return;

    const jobs = await ctx.db
      .query("outreachJobs")
      .withIndex("by_company", (q) => q.eq("companyId", companyId))
      .collect();

    const contacts = await ctx.db
      .query("outreachContacts")
      .withIndex("by_company", (q) => q.eq("companyId", companyId))
      .collect();

    const existingSteps = await ctx.db
      .query("outreachSteps")
      .withIndex("by_company", (q) => q.eq("companyId", companyId))
      .collect();

    const existingLabels = existingSteps.map((s) => s.label.toLowerCase());

    const hasLabel = (keyword: string) =>
      existingLabels.some((l) => l.includes(keyword.toLowerCase()));

    const now = Date.now();
    let order = existingSteps.length;

    const stepsToAdd: Array<{ label: string }> = [];

    const linkedinJobs = jobs.filter((j) => j.source === "linkedin");
    if (linkedinJobs.length > 0 && !hasLabel("linkedin")) {
      stepsToAdd.push({ label: "Apply on LinkedIn" });
    }

    if (company.careersUrl && !hasLabel("company portal")) {
      stepsToAdd.push({ label: "Apply on company portal" });
    }

    if (company.isYcBacked && !hasLabel("yc portal")) {
      stepsToAdd.push({ label: "Apply via YC portal" });
    }

    const contactsWithEmail = contacts.filter((c) => c.email);
    if (contactsWithEmail.length > 0 && !hasLabel("cold email")) {
      stepsToAdd.push({ label: "Send cold emails" });
    }

    const contactsWithLinkedin = contacts.filter((c) => c.linkedinUrl);
    if (contactsWithLinkedin.length > 0 && !hasLabel("linkedin dm")) {
      stepsToAdd.push({ label: "Send LinkedIn DMs" });
    }

    for (const step of stepsToAdd) {
      await ctx.db.insert("outreachSteps", {
        companyId,
        label: step.label,
        status: "pending",
        order: order++,
        isAutoGenerated: true,
        updatedAt: now,
      });
    }

    const jobCount = jobs.length;
    const contactCount = contacts.length;
    const summary = `Research complete: ${jobCount} job${jobCount !== 1 ? "s" : ""} found, ${contactCount} contact${contactCount !== 1 ? "s" : ""} found.`;

    await ctx.db.patch(companyId, {
      researchStatus: "done",
      researchSummary: summary,
      updatedAt: now,
    });
  },
});

// ─── Internal actions ─────────────────────────────────────────────────────────

export const discoverJobs = internalAction({
  args: {
    companyId: v.id("outreachCompanies"),
    companyName: v.string(),
    domain: v.optional(v.string()),
    linkedinUrl: v.optional(v.string()),
    careersUrl: v.optional(v.string()),
    isYcBacked: v.boolean(),
  },
  handler: async (ctx, { companyId, companyName, domain, linkedinUrl: _linkedinUrl, careersUrl, isYcBacked: _isYcBacked }) => {
    type JobPayload = {
      companyId: typeof companyId;
      title: string;
      url: string;
      source: "linkedin" | "careers_page" | "greenhouse" | "lever" | "ashby" | "workable" | "yc" | "wellfound" | "instahyre" | "naukri";
      location?: string;
      description?: string;
    };

    const discovered: JobPayload[] = [];

    // Careers page scraping
    if (domain) {
      const urlsToTry = careersUrl
        ? [careersUrl]
        : [
            `https://${domain}/careers`,
            `https://${domain}/jobs`,
            `https://${domain}/open-positions`,
          ];

      for (const url of urlsToTry) {
        try {
          const res = await fetch(url, {
            headers: {
              "User-Agent":
                "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
            },
            redirect: "follow",
          });
          if (!res.ok) continue;

          const html = await res.text();
          const finalUrl = res.url;

          // Detect ATS redirects
          let atsSource: JobPayload["source"] = "careers_page";
          let atsJobsUrl: string | null = null;

          if (finalUrl.includes("greenhouse.io") || html.includes("greenhouse.io/embed")) {
            atsSource = "greenhouse";
            const ghMatch = html.match(/https:\/\/boards\.greenhouse\.io\/[^"'\s]+/);
            if (ghMatch) atsJobsUrl = ghMatch[0];
          } else if (finalUrl.includes("lever.co") || html.includes("jobs.lever.co")) {
            atsSource = "lever";
            const leverMatch = html.match(/https:\/\/jobs\.lever\.co\/[^"'\s]+/);
            if (leverMatch) atsJobsUrl = leverMatch[0];
          } else if (finalUrl.includes("ashbyhq.com") || html.includes("ashbyhq.com")) {
            atsSource = "ashby";
          } else if (finalUrl.includes("workable.com") || html.includes("workable.com")) {
            atsSource = "workable";
          }

          // Extract job titles + links from common HTML patterns
          const jobLinkPattern =
            /<a[^>]+href=["']([^"']+)["'][^>]*>([^<]{10,120})<\/a>/gi;
          let match: RegExpExecArray | null;
          const seenTitles = new Set<string>();

          while ((match = jobLinkPattern.exec(html)) !== null) {
            const href = match[1];
            const text = match[2].trim().replace(/\s+/g, " ");

            // Heuristic: skip navigation links, keep job-looking titles
            if (text.split(" ").length < 2 || text.split(" ").length > 12) continue;
            if (/about|blog|contact|privacy|terms|login|sign/i.test(text)) continue;
            if (seenTitles.has(text.toLowerCase())) continue;
            seenTitles.add(text.toLowerCase());

            const jobUrl = href.startsWith("http")
              ? href
              : href.startsWith("/")
              ? `https://${domain}${href}`
              : `${url}/${href}`;

            discovered.push({
              companyId,
              title: text,
              url: jobUrl,
              source: atsSource,
            });

            if (discovered.length >= 20) break;
          }

          if (discovered.length > 0) {
            // Update careersUrl if we found it
            if (!careersUrl) {
              await ctx.runMutation(internal.companyResearch.enrichCompany, {
                companyId,
                careersUrl: url,
              });
            }
            break;
          }

          // Suppress unused variable warning
          void atsJobsUrl;
        } catch {
          // Try next URL
        }
      }
    }

    // LinkedIn jobs stub — returns empty (requires OAuth)
    // YC / Wellfound stubs — returns empty for now

    if (discovered.length > 0) {
      await ctx.runMutation(internal.outreachJobs.batchCreate, {
        jobs: discovered,
      });
    }

    await ctx.runMutation(internal.companyResearch.finalizeResearch, {
      companyId,
    });
  },
});

export const findContacts = internalAction({
  args: {
    companyId: v.id("outreachCompanies"),
    companyName: v.string(),
    domain: v.optional(v.string()),
    tier: v.optional(v.union(v.literal("tier1"), v.literal("tier2"), v.literal("tier3"))),
  },
  handler: async (ctx, { companyId, companyName: _companyName, domain, tier }) => {
    const apolloKey = process.env.APOLLO_API_KEY;
    if (!apolloKey || !domain) {
      await ctx.runMutation(internal.companyResearch.finalizeResearch, { companyId });
      return;
    }

    const tier1Titles = [
      "CTO",
      "VP Engineering",
      "Head of Engineering",
      "Director of Engineering",
      "Engineering Manager",
      "Founder",
      "CEO",
    ];
    const tier2Titles = [
      "Recruiter",
      "Senior Recruiter",
      "Talent Acquisition",
      "HR Manager",
      "Technical Recruiter",
    ];

    const targetTitles = tier === "tier2" ? tier2Titles : tier1Titles;
    const contactTier = tier ?? "tier1";

    try {
      const res = await fetch("https://api.apollo.io/api/v1/mixed_people/search", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "X-Api-Key": apolloKey,
        },
        body: JSON.stringify({
          q_organization_domains: domain,
          q_titles: targetTitles,
          per_page: 10,
        }),
      });

      if (!res.ok) {
        await ctx.runMutation(internal.companyResearch.finalizeResearch, { companyId });
        return;
      }

      const data = await res.json();
      const people: Array<{
        name?: string;
        first_name?: string;
        last_name?: string;
        title?: string;
        linkedin_url?: string;
        email?: string;
        phone_numbers?: Array<{ sanitized_number?: string }>;
        photo_url?: string;
        headline?: string;
      }> = data.people ?? [];

      for (const person of people) {
        const name =
          person.name ??
          [person.first_name, person.last_name].filter(Boolean).join(" ");
        if (!name) continue;

        await ctx.runMutation(internal.outreachContacts.createFromResearch, {
          companyId,
          name,
          title: person.title,
          linkedinUrl: person.linkedin_url,
          email: person.email,
          phone: person.phone_numbers?.[0]?.sanitized_number,
          profilePictureUrl: person.photo_url,
          headline: person.headline,
          source: "apollo",
          tier: contactTier,
        });
      }
    } catch {
      // Apollo search failed — finalize anyway
    }

    await ctx.runMutation(internal.companyResearch.finalizeResearch, { companyId });
  },
});

// ─── Public action ────────────────────────────────────────────────────────────

export const researchCompany = action({
  args: {
    companyId: v.id("outreachCompanies"),
    input: v.optional(v.string()),
  },
  handler: async (ctx, { companyId, input }) => {
    // Set status to researching
    await ctx.runMutation(internal.companyResearch.updateResearchStatus, {
      companyId,
      status: "researching",
    });

    // Fetch current company record
    const company = await ctx.runQuery(api.outreachCompanies.get, { id: companyId });
    if (!company) throw new Error("Company not found");

    let domain = company.domain;
    let linkedinUrl = company.linkedinUrl;
    let websiteUrl = company.websiteUrl;

    // Resolve identity from input if provided
    if (input) {
      try {
        const parsed = new URL(input.startsWith("http") ? input : `https://${input}`);
        if (parsed.hostname.includes("linkedin.com")) {
          linkedinUrl = input.startsWith("http") ? input : `https://${input}`;
        } else {
          websiteUrl = input.startsWith("http") ? input : `https://${input}`;
          domain = parsed.hostname.replace("www.", "");
        }
      } catch {
        // input is a plain name — keep existing fields
      }
    }

    // Enrich with Clearbit logo if we have a domain
    if (domain && !company.logoUrl) {
      const logoUrl = `https://logo.clearbit.com/${domain}`;
      await ctx.runMutation(internal.companyResearch.enrichCompany, {
        companyId,
        domain,
        logoUrl,
        linkedinUrl,
        websiteUrl,
      });
    } else if (domain || linkedinUrl || websiteUrl) {
      await ctx.runMutation(internal.companyResearch.enrichCompany, {
        companyId,
        domain,
        linkedinUrl,
        websiteUrl,
      });
    }

    // Check YC backing
    let isYcBacked = company.isYcBacked;
    if (!isYcBacked && domain) {
      try {
        const ycRes = await fetch(
          `https://www.ycombinator.com/companies?q=${encodeURIComponent(company.name)}`,
          { headers: { "User-Agent": "Mozilla/5.0" } }
        );
        if (ycRes.ok) {
          const html = await ycRes.text();
          isYcBacked = html.toLowerCase().includes(company.name.toLowerCase());
          if (isYcBacked) {
            await ctx.runMutation(internal.companyResearch.enrichCompany, {
              companyId,
              isYcBacked: true,
            });
          }
        }
      } catch {
        // YC check failed
      }
    }

    // Schedule job discovery and contact finding in parallel
    await ctx.scheduler.runAfter(0, internal.companyResearch.discoverJobs, {
      companyId,
      companyName: company.name,
      domain,
      linkedinUrl,
      careersUrl: company.careersUrl,
      isYcBacked,
    });

    await ctx.scheduler.runAfter(0, internal.companyResearch.findContacts, {
      companyId,
      companyName: company.name,
      domain,
      tier: "tier1",
    });
  },
});
