import { action } from "./_generated/server";
import { api } from "./_generated/api";

export const seedInitialData = action({
  args: {},
  handler: async (ctx): Promise<{ fibrId: string; zenskarId: string; gushworkId: string }> => {
    // 1. Fibr.ai
    const fibrId = await ctx.runMutation(api.outreachCompanies.create, {
      name: "Fibr.ai",
      domain: "fibr.ai",
      logoUrl: "https://logo.clearbit.com/fibr.ai",
      websiteUrl: "https://fibr.ai",
      isYcBacked: false,
      status: "active",
    });
    await ctx.runMutation(api.outreachSteps.create, {
      companyId: fibrId,
      label: "LinkedIn cold messages",
      status: "done",
      order: 0,
    });
    await ctx.runMutation(api.outreachSteps.create, {
      companyId: fibrId,
      label: "Resume shared",
      status: "done",
      order: 1,
    });
    await ctx.runMutation(api.outreachSteps.create, {
      companyId: fibrId,
      label: "Follow-up",
      status: "pending",
      order: 2,
    });
    await ctx.runMutation(api.outreachContacts.create, {
      companyId: fibrId,
      name: "Ankur Goyal",
      title: "CEO",
      linkedinUrl: "https://www.linkedin.com/in/ankurgoyal1/",
      source: "manual",
    });
    await ctx.runMutation(api.outreachContacts.create, {
      companyId: fibrId,
      name: "Pritam Roy",
      title: "Founder",
      linkedinUrl: "https://www.linkedin.com/in/pritamroy/",
      source: "manual",
    });

    // 2. Zenskar
    const zenskarId = await ctx.runMutation(api.outreachCompanies.create, {
      name: "Zenskar",
      domain: "zenskar.com",
      logoUrl: "https://logo.clearbit.com/zenskar.com",
      websiteUrl: "https://zenskar.com",
      isYcBacked: true,
      roleAppliedFor: "Founding Engineer",
      status: "active",
    });
    await ctx.runMutation(api.outreachSteps.create, {
      companyId: zenskarId,
      label: "Instahyre application",
      status: "done",
      order: 0,
    });
    await ctx.runMutation(api.outreachSteps.create, {
      companyId: zenskarId,
      label: "Cold emails",
      status: "pending",
      order: 1,
    });
    await ctx.runMutation(api.outreachSteps.create, {
      companyId: zenskarId,
      label: "Apply via YC Work at a Startup portal",
      status: "pending",
      order: 2,
      isAutoGenerated: true,
    });

    // 3. Gushwork.ai
    const gushworkId = await ctx.runMutation(api.outreachCompanies.create, {
      name: "Gushwork.ai",
      domain: "gushwork.ai",
      logoUrl: "https://logo.clearbit.com/gushwork.ai",
      websiteUrl: "https://gushwork.ai",
      isYcBacked: false,
      status: "active",
    });
    await ctx.runMutation(api.outreachSteps.create, {
      companyId: gushworkId,
      label: "LinkedIn cold messages",
      status: "done",
      order: 0,
    });
    await ctx.runMutation(api.outreachSteps.create, {
      companyId: gushworkId,
      label: "Follow-up",
      status: "pending",
      order: 1,
    });
    await ctx.runMutation(api.outreachContacts.create, {
      companyId: gushworkId,
      name: "Debangi Chakraborti",
      source: "manual",
    });
    await ctx.runMutation(api.outreachContacts.create, {
      companyId: gushworkId,
      name: "Himanshu Bamoria",
      source: "manual",
    });

    return { fibrId, zenskarId, gushworkId };
  },
});
