import type { Id } from "@/convex/_generated/dataModel";

export interface OutreachCompany {
  _id: Id<"outreachCompanies">;
  name: string;
  domain?: string;
  logoUrl?: string;
  linkedinUrl?: string;
  websiteUrl?: string;
  isYcBacked: boolean;
  fundingStage?: string;
  description?: string;
  userId: string;
  status: "active" | "paused" | "closed";
  roleAppliedFor?: string;
  updatedAt: number;
  employeeCount?: number;
  industry?: string;
  careersUrl?: string;
  researchStatus?: "pending" | "researching" | "done" | "failed";
  researchSummary?: string;
}

export type ContactTier = "tier1" | "tier2" | "tier3";

export interface OutreachContact {
  _id: Id<"outreachContacts">;
  companyId: Id<"outreachCompanies">;
  name: string;
  title?: string;
  linkedinUrl?: string;
  email?: string;
  phone?: string;
  profilePictureUrl?: string;
  headline?: string;
  source: "manual" | "apollo" | "linkedin";
  followUpEnabled?: boolean;
  followUpStoppedReason?: FollowUpStoppedReason;
  updatedAt: number;
  tier?: ContactTier;
}

export interface OutreachStep {
  _id: Id<"outreachSteps">;
  companyId: Id<"outreachCompanies">;
  label: string;
  status: "pending" | "done" | "skipped";
  order: number;
  isAutoGenerated?: boolean;
  updatedAt: number;
}

export interface OutreachMessage {
  _id: Id<"outreachMessages">;
  contactId: Id<"outreachContacts">;
  companyId: Id<"outreachCompanies">;
  channel: MessageChannel;
  body: string;
  sentAt: number;
  direction: "outbound" | "inbound";
  updatedAt: number;
}

export interface OutreachGuidanceEntry {
  _id: Id<"outreachGuidance">;
  contactId: Id<"outreachContacts">;
  channel: GuidanceChannel;
  guidance: string;
  updatedAt: number;
}

export type MessageChannel =
  | "linkedin_dm"
  | "linkedin_connection"
  | "email"
  | "whatsapp";

export type GuidanceChannel = "linkedin" | "email" | "whatsapp";

export type CompanyStatusFilter = "all" | "active" | "paused" | "closed";

export const STATUS_TABS: { key: CompanyStatusFilter; label: string }[] = [
  { key: "all", label: "All" },
  { key: "active", label: "Active" },
  { key: "paused", label: "Paused" },
  { key: "closed", label: "Closed" },
];

export const CHANNEL_LABELS: Record<MessageChannel, string> = {
  linkedin_dm: "LinkedIn DM",
  linkedin_connection: "Connection Request",
  email: "Email",
  whatsapp: "WhatsApp",
};

export const CHANNEL_COLORS: Record<MessageChannel, string> = {
  linkedin_dm:
    "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
  linkedin_connection:
    "bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300",
  email:
    "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
  whatsapp:
    "bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300",
};

export const GUIDANCE_CHANNELS: {
  key: GuidanceChannel;
  label: string;
}[] = [
  { key: "linkedin", label: "LinkedIn" },
  { key: "email", label: "Email" },
  { key: "whatsapp", label: "WhatsApp" },
];

export type FollowUpStoppedReason = "manual" | "replied" | "closed";

export type ReminderStatus = "pending" | "notified" | "acted" | "dismissed";

export interface FollowUpReminder {
  _id: Id<"followUpReminders">;
  contactId: Id<"outreachContacts">;
  companyId: Id<"outreachCompanies">;
  channel: "linkedin_dm" | "linkedin_connection" | "email";
  dueAt: number;
  status: ReminderStatus;
  lastOutboundMessageId?: Id<"outreachMessages">;
  updatedAt: number;
}

export const STOPPED_REASON_LABELS: Record<FollowUpStoppedReason, string> = {
  manual: "Stopped manually",
  replied: "Contact replied",
  closed: "Company closed",
};

export type JobSource =
  | "linkedin" | "careers_page" | "greenhouse" | "lever"
  | "ashby" | "workable" | "yc" | "wellfound" | "instahyre" | "naukri";

export type JobStatus = "new" | "applied" | "skipped";

export interface OutreachJob {
  _id: Id<"outreachJobs">;
  companyId: Id<"outreachCompanies">;
  title: string;
  url: string;
  source: JobSource;
  location?: string;
  workMode?: "remote" | "hybrid" | "onsite" | "unknown";
  status: JobStatus;
  description?: string;
  postedAt?: number;
  appliedAt?: number;
  appliedVia?: string;
  appliedNotes?: string;
  updatedAt: number;
}

export const SOURCE_COLORS: Record<JobSource, string> = {
  linkedin: "bg-[#0A66C2] text-white",
  careers_page: "bg-emerald-500 text-white",
  greenhouse: "bg-[#3AB549] text-white",
  lever: "bg-[#5C6BC0] text-white",
  ashby: "bg-[#6366F1] text-white",
  workable: "bg-[#1DA1F2] text-white",
  yc: "bg-[#F26522] text-white",
  wellfound: "bg-zinc-800 text-white dark:bg-zinc-200 dark:text-zinc-800",
  instahyre: "bg-[#FF6B35] text-white",
  naukri: "bg-[#457EFF] text-white",
};

export const SOURCE_LABELS: Record<JobSource, string> = {
  linkedin: "LinkedIn",
  careers_page: "Careers",
  greenhouse: "Greenhouse",
  lever: "Lever",
  ashby: "Ashby",
  workable: "Workable",
  yc: "YC",
  wellfound: "Wellfound",
  instahyre: "Instahyre",
  naukri: "Naukri",
};

export const SOURCE_BORDER_COLORS: Record<JobSource, string> = {
  linkedin: "border-l-[#0A66C2]",
  careers_page: "border-l-emerald-500",
  greenhouse: "border-l-[#3AB549]",
  lever: "border-l-[#5C6BC0]",
  ashby: "border-l-[#6366F1]",
  workable: "border-l-[#1DA1F2]",
  yc: "border-l-[#F26522]",
  wellfound: "border-l-zinc-800",
  instahyre: "border-l-[#FF6B35]",
  naukri: "border-l-[#457EFF]",
};

export const TIER_LABELS: Record<ContactTier, string> = {
  tier1: "Decision Maker",
  tier2: "Recruiter",
  tier3: "Referral",
};

export const TIER_COLORS: Record<ContactTier, string> = {
  tier1: "bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300",
  tier2: "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
  tier3: "bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-400",
};

export const APPLIED_VIA_OPTIONS = [
  { key: "linkedin_easy_apply", label: "LinkedIn Easy Apply", color: "bg-[#0A66C2]" },
  { key: "company_portal", label: "Company Portal", color: "bg-emerald-500" },
  { key: "yc", label: "YC Portal", color: "bg-[#F26522]" },
  { key: "referral", label: "Referral", color: "bg-purple-500" },
  { key: "email", label: "Email", color: "bg-amber-500" },
  { key: "other", label: "Other", color: "bg-zinc-500" },
];

// --- Contact Stage Pipeline ---

export type ContactStage =
  | "request_sent"
  | "accepted"
  | "dm_sent"
  | "replied"
  | "no_response";

export const STAGE_ORDER: ContactStage[] = [
  "request_sent",
  "accepted",
  "dm_sent",
  "replied",
];

export const STAGE_LABELS: Record<ContactStage, string> = {
  request_sent: "Request Sent",
  accepted: "Connected",
  dm_sent: "DM Sent",
  replied: "Replied",
  no_response: "No Response",
};

export const STAGE_COLORS: Record<ContactStage, string> = {
  request_sent: "text-blue-400 bg-blue-400",
  accepted: "text-green-400 bg-green-400",
  dm_sent: "text-purple-400 bg-purple-400",
  replied: "text-emerald-400 bg-emerald-400",
  no_response: "text-red-400 bg-red-400",
};

// --- Next Step Recommendation ---

export interface NextStep {
  action: string;
  dueLabel: string;
  urgency: "on_track" | "due_soon" | "overdue" | "done";
}

export const URGENCY_COLORS: Record<NextStep["urgency"], string> = {
  on_track: "bg-blue-500/10 border-blue-500/30 text-blue-300",
  due_soon: "bg-amber-500/10 border-amber-500/30 text-amber-300",
  overdue: "bg-red-500/10 border-red-500/30 text-red-300",
  done: "bg-emerald-500/10 border-emerald-500/30 text-emerald-300",
};

// --- Company Outreach Auto-Status ---

export type CompanyOutreachStatus =
  | "warming_up"
  | "needs_outreach"
  | "following_up"
  | "in_conversation"
  | "going_cold"
  | "done";

export const COMPANY_OUTREACH_LABELS: Record<CompanyOutreachStatus, string> = {
  warming_up: "Warming Up",
  needs_outreach: "Needs Outreach",
  following_up: "Following Up",
  in_conversation: "In Conversation",
  going_cold: "Going Cold",
  done: "Done",
};

export const COMPANY_OUTREACH_COLORS: Record<CompanyOutreachStatus, string> = {
  warming_up: "bg-sky-500/20 text-sky-300 border-sky-500/30",
  needs_outreach: "bg-blue-500/20 text-blue-300 border-blue-500/30",
  following_up: "bg-amber-500/20 text-amber-300 border-amber-500/30",
  in_conversation: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
  going_cold: "bg-red-500/20 text-red-300 border-red-500/30",
  done: "bg-zinc-500/20 text-zinc-400 border-zinc-500/30",
};

export const COMPANY_BORDER_COLORS: Record<CompanyOutreachStatus, string> = {
  warming_up: "border-l-sky-500",
  needs_outreach: "border-l-blue-500",
  following_up: "border-l-amber-500",
  in_conversation: "border-l-emerald-500",
  going_cold: "border-l-red-500",
  done: "border-l-zinc-500",
};

export interface OutreachFunnel {
  reached: number;
  connected: number;
  dmed: number;
  replied: number;
  total: number;
}
