import type { Id } from "@/convex/_generated/dataModel";

export interface OutreachCompany {
  _id: Id<"outreachCompanies">;
  name: string;
  domain?: string;
  logoUrl?: string;
  linkedinUrl?: string;
  websiteUrl?: string;
  isYcBacked: boolean;
  fundingStage?: string;
  description?: string;
  userId: string;
  status: "active" | "paused" | "closed";
  roleAppliedFor?: string;
  updatedAt: number;
}

export interface OutreachContact {
  _id: Id<"outreachContacts">;
  companyId: Id<"outreachCompanies">;
  name: string;
  title?: string;
  linkedinUrl?: string;
  email?: string;
  phone?: string;
  profilePictureUrl?: string;
  headline?: string;
  source: "manual" | "apollo" | "linkedin";
  updatedAt: number;
}

export interface OutreachStep {
  _id: Id<"outreachSteps">;
  companyId: Id<"outreachCompanies">;
  label: string;
  status: "pending" | "done" | "skipped";
  order: number;
  isAutoGenerated?: boolean;
  updatedAt: number;
}

export interface OutreachMessage {
  _id: Id<"outreachMessages">;
  contactId: Id<"outreachContacts">;
  companyId: Id<"outreachCompanies">;
  channel: MessageChannel;
  body: string;
  sentAt: number;
  direction: "outbound" | "inbound";
  updatedAt: number;
}

export interface OutreachGuidanceEntry {
  _id: Id<"outreachGuidance">;
  contactId: Id<"outreachContacts">;
  channel: GuidanceChannel;
  guidance: string;
  updatedAt: number;
}

export type MessageChannel =
  | "linkedin_dm"
  | "linkedin_connection"
  | "email"
  | "whatsapp";

export type GuidanceChannel = "linkedin" | "email" | "whatsapp";

export type CompanyStatusFilter = "all" | "active" | "paused" | "closed";

export const STATUS_TABS: { key: CompanyStatusFilter; label: string }[] = [
  { key: "all", label: "All" },
  { key: "active", label: "Active" },
  { key: "paused", label: "Paused" },
  { key: "closed", label: "Closed" },
];

export const CHANNEL_LABELS: Record<MessageChannel, string> = {
  linkedin_dm: "LinkedIn DM",
  linkedin_connection: "Connection Request",
  email: "Email",
  whatsapp: "WhatsApp",
};

export const CHANNEL_COLORS: Record<MessageChannel, string> = {
  linkedin_dm:
    "bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300",
  linkedin_connection:
    "bg-sky-100 text-sky-700 dark:bg-sky-900/40 dark:text-sky-300",
  email:
    "bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300",
  whatsapp:
    "bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300",
};

export const GUIDANCE_CHANNELS: {
  key: GuidanceChannel;
  label: string;
}[] = [
  { key: "linkedin", label: "LinkedIn" },
  { key: "email", label: "Email" },
  { key: "whatsapp", label: "WhatsApp" },
];

export type FollowUpStoppedReason = "manual" | "replied" | "closed";

export type ReminderStatus = "pending" | "notified" | "acted" | "dismissed";

export interface FollowUpReminder {
  _id: Id<"followUpReminders">;
  contactId: Id<"outreachContacts">;
  companyId: Id<"outreachCompanies">;
  channel: "linkedin_dm" | "linkedin_connection" | "email";
  dueAt: number;
  status: ReminderStatus;
  lastOutboundMessageId?: Id<"outreachMessages">;
  updatedAt: number;
}

export const STOPPED_REASON_LABELS: Record<FollowUpStoppedReason, string> = {
  manual: "Stopped manually",
  replied: "Contact replied",
  closed: "Company closed",
};
