import { mutation, query, internalMutation } from "./_generated/server";
import { v } from "convex/values";
import { requirePerson } from "./helpers/auth";

const stepStatusValidator = v.union(
  v.literal("pending"),
  v.literal("done"),
  v.literal("skipped")
);

export const listByCompany = query({
  args: { companyId: v.id("outreachCompanies") },
  handler: async (ctx, { companyId }) => {
    const steps = await ctx.db
      .query("outreachSteps")
      .withIndex("by_company", (q) => q.eq("companyId", companyId))
      .collect();
    return steps.sort((a, b) => a.order - b.order);
  },
});

export const create = mutation({
  args: {
    companyId: v.id("outreachCompanies"),
    label: v.string(),
    status: v.optional(stepStatusValidator),
    order: v.optional(v.number()),
    isAutoGenerated: v.optional(v.boolean()),
  },
  handler: async (ctx, args) => {
    await requirePerson(ctx);
    let order = args.order;
    if (order === undefined) {
      const existing = await ctx.db
        .query("outreachSteps")
        .withIndex("by_company", (q) => q.eq("companyId", args.companyId))
        .collect();
      order = existing.length;
    }
    return await ctx.db.insert("outreachSteps", {
      companyId: args.companyId,
      label: args.label,
      status: args.status ?? "pending",
      order,
      isAutoGenerated: args.isAutoGenerated,
      updatedAt: Date.now(),
    });
  },
});

export const updateStatus = mutation({
  args: {
    id: v.id("outreachSteps"),
    status: stepStatusValidator,
  },
  handler: async (ctx, { id, status }) => {
    await requirePerson(ctx);
    await ctx.db.patch(id, { status, updatedAt: Date.now() });
  },
});

export const updateLabel = mutation({
  args: {
    id: v.id("outreachSteps"),
    label: v.string(),
  },
  handler: async (ctx, { id, label }) => {
    await requirePerson(ctx);
    await ctx.db.patch(id, { label, updatedAt: Date.now() });
  },
});

export const reorder = mutation({
  args: {
    steps: v.array(
      v.object({ id: v.id("outreachSteps"), order: v.number() })
    ),
  },
  handler: async (ctx, { steps }) => {
    await requirePerson(ctx);
    const now = Date.now();
    for (const { id, order } of steps) {
      await ctx.db.patch(id, { order, updatedAt: now });
    }
  },
});

export const remove = mutation({
  args: { id: v.id("outreachSteps") },
  handler: async (ctx, { id }) => {
    await requirePerson(ctx);
    await ctx.db.delete(id);
  },
});

export const createInternal = internalMutation({
  args: {
    companyId: v.id("outreachCompanies"),
    label: v.string(),
    status: v.optional(stepStatusValidator),
    order: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    let order = args.order;
    if (order === undefined) {
      const existing = await ctx.db
        .query("outreachSteps")
        .withIndex("by_company", (q) => q.eq("companyId", args.companyId))
        .collect();
      order = existing.length;
    }
    return await ctx.db.insert("outreachSteps", {
      companyId: args.companyId,
      label: args.label,
      status: args.status ?? "pending",
      order,
      updatedAt: Date.now(),
    });
  },
});

export const listAllWithCompany = query({
  args: {},
  handler: async (ctx) => {
    const { getCurrentPerson } = await import("./helpers/auth");
    const person = await getCurrentPerson(ctx);
    if (!person) return [];
    const userId = person.clerkTokenIdentifier!;

    const companies = await ctx.db
      .query("outreachCompanies")
      .withIndex("by_user", (q) => q.eq("userId", userId))
      .collect();

    const results = [];
    for (const company of companies) {
      const steps = await ctx.db
        .query("outreachSteps")
        .withIndex("by_company", (q) => q.eq("companyId", company._id))
        .collect();
      for (const step of steps) {
        results.push({
          ...step,
          companyName: company.name,
          companyDomain: company.domain,
          companyLogoUrl: company.logoUrl,
          companyStatus: company.status,
          roleAppliedFor: company.roleAppliedFor,
        });
      }
    }

    return results.sort((a, b) => {
      // Pending first, then by updatedAt desc
      if (a.status === "pending" && b.status !== "pending") return -1;
      if (a.status !== "pending" && b.status === "pending") return 1;
      return b.updatedAt - a.updatedAt;
    });
  },
});
