import { mutation } from "./_generated/server";
import { v } from "convex/values";

export const clearAndReseed = mutation({
  args: { userId: v.string() },
  handler: async (ctx, { userId }) => {
    const now = Date.now();

    // Clear existing outreach data
    const companies = await ctx.db.query("outreachCompanies").collect();
    for (const c of companies) {
      const contacts = await ctx.db.query("outreachContacts").withIndex("by_company", (q) => q.eq("companyId", c._id)).collect();
      for (const contact of contacts) {
        const msgs = await ctx.db.query("outreachMessages").withIndex("by_contact", (q) => q.eq("contactId", contact._id)).collect();
        for (const m of msgs) await ctx.db.delete(m._id);
        const guidance = await ctx.db.query("outreachGuidance").withIndex("by_contact", (q) => q.eq("contactId", contact._id)).collect();
        for (const g of guidance) await ctx.db.delete(g._id);
        await ctx.db.delete(contact._id);
      }
      const steps = await ctx.db.query("outreachSteps").withIndex("by_company", (q) => q.eq("companyId", c._id)).collect();
      for (const s of steps) await ctx.db.delete(s._id);
      await ctx.db.delete(c._id);
    }

    // 1. Fibr.ai
    const fibrId = await ctx.db.insert("outreachCompanies", {
      name: "Fibr.ai", domain: "fibr.ai", logoUrl: "https://logo.clearbit.com/fibr.ai",
      websiteUrl: "https://fibr.ai", isYcBacked: false, userId, status: "active", updatedAt: now,
    });
    await ctx.db.insert("outreachSteps", { companyId: fibrId, label: "LinkedIn cold messages", status: "done", order: 0, updatedAt: now });
    await ctx.db.insert("outreachSteps", { companyId: fibrId, label: "Resume shared", status: "done", order: 1, updatedAt: now });
    await ctx.db.insert("outreachSteps", { companyId: fibrId, label: "Follow-up", status: "pending", order: 2, updatedAt: now });
    await ctx.db.insert("outreachContacts", { companyId: fibrId, name: "Ankur Goyal", title: "CEO", linkedinUrl: "https://www.linkedin.com/in/ankurgoyal1/", source: "manual", updatedAt: now });
    await ctx.db.insert("outreachContacts", { companyId: fibrId, name: "Pritam Roy", title: "Founder", linkedinUrl: "https://www.linkedin.com/in/pritamroy/", source: "manual", updatedAt: now });

    // 2. Zenskar
    const zenskarId = await ctx.db.insert("outreachCompanies", {
      name: "Zenskar", domain: "zenskar.com", logoUrl: "https://logo.clearbit.com/zenskar.com",
      websiteUrl: "https://zenskar.com", isYcBacked: true, roleAppliedFor: "Founding Engineer",
      userId, status: "active", updatedAt: now,
    });
    await ctx.db.insert("outreachSteps", { companyId: zenskarId, label: "Instahyre application", status: "done", order: 0, updatedAt: now });
    await ctx.db.insert("outreachSteps", { companyId: zenskarId, label: "Cold emails", status: "pending", order: 1, updatedAt: now });
    await ctx.db.insert("outreachSteps", { companyId: zenskarId, label: "Apply via YC Work at a Startup portal", status: "pending", order: 2, isAutoGenerated: true, updatedAt: now });

    // 3. Gushwork.ai
    const gushworkId = await ctx.db.insert("outreachCompanies", {
      name: "Gushwork.ai", domain: "gushwork.ai", logoUrl: "https://logo.clearbit.com/gushwork.ai",
      websiteUrl: "https://gushwork.ai", isYcBacked: false, userId, status: "active", updatedAt: now,
    });
    await ctx.db.insert("outreachSteps", { companyId: gushworkId, label: "LinkedIn cold messages", status: "done", order: 0, updatedAt: now });
    await ctx.db.insert("outreachSteps", { companyId: gushworkId, label: "Follow-up", status: "pending", order: 1, updatedAt: now });
    await ctx.db.insert("outreachContacts", { companyId: gushworkId, name: "Debangi Chakraborti", source: "manual", updatedAt: now });
    await ctx.db.insert("outreachContacts", { companyId: gushworkId, name: "Himanshu Bamoria", source: "manual", updatedAt: now });

    return { fibrId, zenskarId, gushworkId };
  },
});
